name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black # flake8 mypy  # Add other linters or static analyzers here

      - name: Run Black
        run: black --check .

      # - name: Run Flake8
      #   run: flake8 .

      # - name: Run MyPy
      #   run: mypy .